server:
  port: 8801

register:
  host: ${RGISTER_HOST:127.0.0.1}
  port: ${RGISTER_PORT:8848}
  group: ${RGISTER_GROUP:BDD_GROUP}
  active: ${RGISTER_ACTIVE:dev}
  namespace: ${RGISTER_NAMESPACE:b27a663c-6586-4bbb-a14b-52fe8ed115c1}
  refresh: ${RGISTER_REFRESH:true}
  username: ${RGISTER_USERNAME:nacos}
  password: ${RGISTER_PASSWORD:nacos}

spring:
  application:
    name: bdd-cloud-service-upms
  config:
    import:
#      - optional:nacos:application-${register.active}.yaml
      - optional:nacos:${spring.application.name}-${register.active}.yaml
  # 安全配置
  cloud:
    nacos:
#      username: ${register.username}
#      password: ${register.password}
      discovery:
        server-addr: ${register.host}:${register.port}
        group: ${register.group}
        namespace: ${register.namespace}
        watch:
          enabled: true
      #        watch-delay: 1000
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        group: ${spring.cloud.nacos.discovery.group}
        namespace: ${spring.cloud.nacos.discovery.namespace}
        refresh-enabled: ${register.refresh}



