server:
  port: 8803
spring:
  application:
    name: by-cloud-gateway
  config:
    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}-dev
  cloud:
    nacos:
      server:
        port: 8848
      discovery:
        server-addr: localhost:${spring.cloud.nacos.server.port}
        namespace: b27a663c-6586-4bbb-a14b-52fe8ed115c1
        group: BDD_GROUP
      config:
        server-addr: localhost:${spring.cloud.nacos.server.port}
        file-extension: yaml
        namespace: b27a663c-6586-4bbb-a14b-52fe8ed115c1
        group: BDD_GROUP
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bdd-cloud-service-upms
          uri: lb://bdd-cloud-service-upms
          predicates:
            - Path=/sysMenu/**,/sysUser/**
